### ISSUE TITLE
Icorrect table rendering

### ISSUE THREAD

**Issue by nguyenthanhvuh** [bastibe/org-static-blog#120] opened 2023-04-30 23:52 UTC
My `org`  file has table but the generated html file shows a table without border.  Direct exports to html from the `org` file generates the expected table with border. This is a strange bug so I am not sure if it's my specific setting or not.

Example:  my `org`  https://nguyenthanhvuh.github.io/org/test.org, which has a table, but outputs this html  post https://nguyenthanhvuh.github.io/posts/test.html, which does not have the proper table.

**Comment by bastibe** [comment] 2023-05-03 16:42
Strange. Tables work fine on my end. Do you have any org-specific customizations that might cause this? What versions of Emacs and Org are you using?

**Comment by nguyenthanhvuh** [comment] 2023-06-03 03:42
sorry for the late reply. I checked but don't see any org-specific settings that would affect this. I also disable all my org settings and still have same issue.  Emacs 28.2 and org mode 9.5.5

**Comment by bastibe** [comment] 2023-06-03 07:42
This is probably not an issue with org-static-blog, I'm afraid. Org-static-blog really doesn't touch org's export facilities, but merely uses them.

That said, your exported table looks perfectly to me. What is it that makes it "wrong" in your eyes?

**Comment by nguyenthanhvuh** [comment] 2023-06-03 20:31
as mentioned in the first post, the issue is that the table doesn't have borders.  Tables from default html exports will have borders.  

I look at the html code of the one generated by `org-static-blog` and one generated directly from `org-mode` and found that the direct one has this code

```
<table border="2" cellspacing="0" cellpadding="6" rules="groups" frame="hsides">

```
but the one by `org-static-blog` does not.  I know it is strange but it's what it is.

**Comment by nguyenthanhvuh** [comment] 2023-06-03 20:33
this happens on both of my computers (one running FreeBSD and the other Mac OS).  Could you generate tables with borders from `org-static-blog` on your machine?

**Comment by bastibe** [comment] 2023-06-04 09:32
You will need to add your own CSS to make the HTML on your static website look the way you want. That's how org-mode and org-static-blog are intended to be used.

As this is not a bug in org-static-blog, I'll close this issue. Feel free to continue this discussion regardless.

**Closed by bastibe** 2023-06-04 09:32 UTC
